# Generated by Django 5.2.6 on 2025-10-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerDepartmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_disclaimer', models.BooleanField(default=False, help_text='Does this department require disclaimer clearance?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_config', to='assets.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Disclaimer Department Configuration',
                'verbose_name_plural': 'Disclaimer Department Configurations',
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='DisclaimerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='in_progress', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='Current step in the disclaimer flow')),
                ('total_steps', models.PositiveIntegerField(help_text='Total number of steps in the flow')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('process_number', models.PositiveIntegerField(default=1, help_text='Sequential number of this process for the employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_processes', to='assets.employee')),
            ],
            options={
                'verbose_name': 'Disclaimer Process',
                'verbose_name_plural': 'Disclaimer Processes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DisclaimerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Step in the disclaimer flow')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('employee_notes', models.TextField(blank=True, help_text='Notes from employee with the request')),
                ('manager_notes', models.TextField(blank=True, help_text='Response notes from department manager')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (required if rejected)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_requests', to='assets.employee')),
                ('process', models.ForeignKey(help_text='The disclaimer process this request belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='disclaimer.disclaimerprocess')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_disclaimers', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(help_text='Department that needs to approve', on_delete=django.db.models.deletion.CASCADE, related_name='received_disclaimer_requests', to='assets.department')),
            ],
            options={
                'verbose_name': 'Disclaimer Request',
                'verbose_name_plural': 'Disclaimer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentDisclaimerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order in the disclaimer flow (1, 2, 3, ...)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_department', models.ForeignKey(help_text='The department whose employees follow this order', on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_orders', to='assets.department')),
                ('target_department', models.ForeignKey(help_text='Department that needs to approve', on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_targets', to='assets.department')),
            ],
            options={
                'verbose_name': 'Department Disclaimer Order',
                'verbose_name_plural': 'Department Disclaimer Orders',
                'ordering': ['employee_department', 'order'],
                'unique_together': {('employee_department', 'order'), ('employee_department', 'target_department')},
            },
        ),
        migrations.AddConstraint(
            model_name='disclaimerprocess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'in_progress')), fields=('employee',), name='unique_active_in_progress_process'),
        ),
        migrations.AddIndex(
            model_name='disclaimerrequest',
            index=models.Index(fields=['employee', 'status'], name='disclaimer__employe_32ba37_idx'),
        ),
        migrations.AddIndex(
            model_name='disclaimerrequest',
            index=models.Index(fields=['target_department', 'status'], name='disclaimer__target__66c692_idx'),
        ),
        migrations.AddIndex(
            model_name='disclaimerrequest',
            index=models.Index(fields=['process', 'status'], name='disclaimer__process_8d60cb_idx'),
        ),
    ]
