# Generated by Django 5.2.6 on 2025-10-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_reports', models.BooleanField(default=False, help_text='Can this employee access and download reports?')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this permission was granted')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_permission', to='assets.employee', verbose_name='Employee')),
                ('granted_by', models.ForeignKey(help_text='Admin who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Permission',
                'verbose_name_plural': 'Report Permissions',
            },
        ),
    ]
